### ISSUE TITLE
Not compile on beta 2

### ISSUE THREAD

**Issue by Codenator81** [reem/rust-typemap#29]
Compiling typemap v0.2.1
/Users/APoltarjonoks/.cargo/registry/src/github.com-1ecc6299db9ec823/typemap-0.2.1/src/lib.rs:171:1: 171:42 error: the trait `core::marker::Sized` is not implemented for the type `CloneAny` [E0277]
/Users/APoltarjonoks/.cargo/registry/src/github.com-1ecc6299db9ec823/typemap-0.2.1/src/lib.rs:171 unsafe impl UnsafeAnyExt for CloneAny { }
                                                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/APoltarjonoks/.cargo/registry/src/github.com-1ecc6299db9ec823/typemap-0.2.1/src/lib.rs:171:1: 171:42 note: `CloneAny` does not have a constant size known at compile-time
/Users/APoltarjonoks/.cargo/registry/src/github.com-1ecc6299db9ec823/typemap-0.2.1/src/lib.rs:171 unsafe impl UnsafeAnyExt for CloneAny { }

**Comment by reem** [comment]
Fixed!
