### ISSUE TITLE
Specified package has no binaries

### ISSUE THREAD

**Issue by Flaise** [reem/rust-typemap#37]
When I try to install:

    $ cargo install typemap
        Updating registry `https://github.com/rust-lang/crates.io-index`
     Downloading typemap v0.3.3
    error: specified package has no binaries

Did I get the crates.io package name right? Is there something I'm doing wrong?

**Comment by reem** [comment]
`cargo install` is for installing packages that result in a binary - packages with a `main` function. `typemap` is a library, you use it by adding it to your `Cargo.toml` in the project you want to use it in.

See the [crates.io getting started guide](http://doc.crates.io/guide.html) in particular the [adding a dependency](http://doc.crates.io/guide.html#adding-a-dependency) section.
