### ISSUE TITLE
Yank version with "*" deps

### ISSUE THREAD

**Issue by kornelski** [reem/rust-typemap#46]
An old version of `typemap` has dependencies specified with `"*"` version requirement (`phantom = "*"`, `unsafe-any = "*"`).

Crates with such vague dependency versions became unusable, because `*` allows picking too-new semver-incompatible dependencies.
It also breaks Cargo's `minimal-versions` feature, because `*` requirement allows picking very very old dependencies that aren't compatible with Rust 1.0.

Because this old version of `typemap` is unusable and may cause problems for Cargo, I suggest yanking it:

```bash
cargo yank --vers 0.0.3
```

**Comment by sugar700** [comment]
Curiously, it appears that all versions of `typemap` have `*` deps.

**Comment by kornelski** [comment]
Ooof, you're right: 

https://github.com/rust-lang/crates.io-index/blob/master/ty/pe/typemap
